version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  db:
    env_file:
      - .env
    build: ./back-end/database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Europe/Athens" # Timezone for the db

    volumes:
      - ./back-end/database/data:/var/lib/mysql
      - ./back-end/database:/docker-entrypoint-initdb.d
    networks:
      - my-network

  backend:
    env_file:
      - .env
    build:
      context: ./back-end/backend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./back-end/backend/output:/app/output
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: ${CONNECTION_STRING}
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRES_IN_MINUTES: ${JWT_EXPIRES_IN_MINUTES}
      TEACHER_EMAIL: ${TEACHER_EMAIL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - my-network

  phpmyadmin:
    env_file:
      - .env
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - my-network
  front-end:
     build: ./front-end
     container_name: front_end_c
     ports:
       - "3000:3000"
     stdin_open: true
     tty: true
     volumes:
       - ./front-end:/usr/src/app/front_end
       - /usr/src/app/front-end/node_modules
