version: '3.9'

services:
  db:
    env_file:
    - ./backend/.env
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
    # Same here
      - ./backend/output:/app/output
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  phpmyadmin:
    env_file:
    - ./backend/.env
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}