version: '3.9'

networks:
  my-network:
    driver: bridge

services:
  db:
    env_file:
    - ./backend/.env
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./backend/output:/app/output
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: "server=db;port=3306;user=root;password=root;database=clients"
    depends_on:
      - db
    networks:
      - my-network

  phpmyadmin:
    env_file:
    - ./backend/.env
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - my-network
